### ISSUE TITLE
Road Map (v1.0.0)

### ISSUE THREAD

**Issue by ghost** [Devenet/MyMovies#6]
_for stable release of version 1.0.0_
### Installation
- [x] Easy installation
- [x] Create directories if they don't exist
  - [x] `data`
  - [x] `cache` and `cache/imdb`
  - [x] `images`
- [x] Ask prefered language (for IMDB search and results)
### Public
- [x] List of movies (sorted by date of creation) 
- [x] Pagination
- [x] Add search form (in title movie, synopsis and genre)
- [x] Sort movies by best rating (implementation of <del>`Favorites`</del> `Box office`)
- [x] Display movies not yet seen (implementation of <del>`Soon`</del> `Watchlist`)
- [x] Sort movies by genre
- [x] Generate RSS feeds (update when a movie is added or edited)
  - [x] Feed for last movies
  - [x] Feed for Box office
  - [x] Feed for Watchlist
### Administration
- [x] Signin and signout pages
- [x] Display logs of connections and errors
- [x] Add movie
  - [x] Title, synopsis required
  - [x] Import image from an URL
  - [x] Esay way to autocomplete fields with data from IMDB (thanks to Rauks [#2](https://github.com/nicolabricot/myMovies/pull/2))
- [x] Edit or delete a movie
- [x] Update settings
  - [x] Password
  - [x] Title (default: myMovies)
  - [x] Prefered language
  - [x] Number of movies by page for pagination 
- [x] Export movies into a json file (thanks to Rauks [#7](https://github.com/nicolabricot/myMovies/pull/7))
- [x] Import movies from a json file (thanks to Rauks [#7](https://github.com/nicolabricot/myMovies/pull/7))
